name: mc-PlayerVisibility
version: '${project.version}'
main: hu.kxtsoo.playervisibility.PlayerVisibility
api-version: '1.18'
authors: [ kxtsoo ]
folia-supported: true

libraries:
  - dev.dejvokep:boosted-yaml:1.3
  - com.zaxxer:HikariCP:5.1.0
  - com.h2database:h2:2.1.214